# Generated by Django 5.0 on 2024-01-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papeleria', '0002_alter_user_groups_alter_user_user_permissions_ventas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registros',
            name='photo',
        ),
        migrations.AddField(
            model_name='registros',
            name='photoLink',
            field=models.CharField(default=1, max_length=500, verbose_name='PhotoLink'),
            preserve_default=False,
        ),
    ]
